### ISSUE TITLE
How to use command?

### ISSUE THREAD

**Issue by WreckagePE** [Sandertv/BlockSniper#21]
I am trying to use the brush command. Can someone post an example?

**Comment by Sandertv** [comment]
Take a look at the Wiki page. It should clarify a lot!

**Comment by WreckagePE** [comment]
Please can I have a link?

**Comment by Sandertv** [comment]
https://github.com/Sandertv/BlockSniper/wiki

**Comment by Sandertv** [comment]
I'm closing this issue. If you think something isn't right, or got any questions, feel free to tell me.
