### ISSUE TITLE
Ideas!

### ISSUE THREAD

**Issue by WreckagePE** [Sandertv/BlockSniper#23]
#### Versions
* PocketMine version:
* BlockSniper version:
* Game version: PE/W10

#### Crashdump and/or console errors

```
```

**Comment by Sandertv** [comment]
Empty?

**Comment by WreckagePE** [comment]
My phone glitches.. Sorry. I was saying you could add an enhancement, named smooth? In the types. It would make this plugin more like voxelsniper, which would be awesome

**Comment by Sandertv** [comment]
I've been thinking of the same, but I'm not entirely sure yet how the smooth thing from VoxelSniper works, as I don't play MCPC. Could you explain that to me?

**Comment by WreckagePE** [comment]
https://m.youtube.com/watch?v=1d_58g_LtnM
He uses the tool in this, it should help you understand bro :)

**Comment by Sandertv** [comment]
I'm having trouble finding what it actually does. It seems like they removed it from any recent VoxelSniper version.

**Comment by Sandertv** [comment]
Oh, I forgot to mention it. In recent commits I've added the 'melt' type. It's getting close to what the smooth does, just melts away blocks that stick out. You might want to try it out.

**Comment by WreckagePE** [comment]
Wow. That feature you should've mentioned, it's very useful.
Just keep continuing this plugin man, I can see a great future and it could be used on very big servers.
Thanks for replying :) 
Closed

**Comment by Sandertv** [comment]
Great to hear you enjoy using the plugin. Make sure to tell me if you got any other questions or suggestions!
