### ISSUE TITLE
Command Issues

### ISSUE THREAD

**Issue by Mrfanman345** [Sandertv/BlockSniper#24]
#### Description

Since the brush command was changed to the new format I no longer am quite sure how to use it. If you wouldn't mind adding example commands to the wiki or just giving examples here I would greatly appreciate that!
#### Versions
* PocketMine version:
* BlockSniper version: Latest/Self Compiled
* Game version: PE Version 1.0.2

#### Crashdump and/or console errors

```
None
```

**Comment by NGGNewGen** [comment]
Yeah I don't understand the commands either it would be greatly appreciated if someone would upload an example command

**Comment by Sandertv** [comment]
Take a look at the Wiki :)

**Comment by Sandertv** [comment]
As of the changes, this is how you would make a sphere made out of stone and grass:
/b sh sphere (default already)
/b bl stone,grass
/b ty fill (default already)

You could also do this with the normal ways, which would look like this:
/b shape sphere (default already)
/b blocks stone,grass
/b type fill (default already)

**Comment by NGGNewGen** [comment]
Ohhh thanks!

**Comment by Sandertv** [comment]
If I were a youtuber I would gladly give you a tutorial, but too badly I'm not.

**Comment by HimbeersaftLP** [comment]
But you have TV at the end of you name :P (I know what it means, I'm just kidding xD)

I'll do a tutorial about it

**Comment by Sandertv** [comment]
> But you have TV at the end of you name 📦 

Damnit @HimbeersaftLP xD

And you would? Amazing :D

**Comment by HimbeersaftLP** [comment]
LOL, OutLook replaced my ":P" with a cardboard box in the notification mail of your reply xD

<a href='http://i.imgur.com/UdnERQv' title=''><img src='http://i.imgur.com/UdnERQv.jpg' alt='' title='Hosted by imgur.com' /></a>

**Comment by Sandertv** [comment]
Lmao, let's not spam the issue too much :3

**Comment by Sandertv** [comment]
Did you get the information you needed @Mrfanman345? ^^

**Comment by Mrfanman345** [comment]
Yeah it makes A lot more sense now. Only thing is when I use the height variable (he) on cylinders it sets the height 1 more than I set it to but I'll make a separate issue for that.
